### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by vmachacek** [cschleiden/github-actions-hero#10] opened 2020-12-22 16:30 UTC
both of those urls are showing An unexpected error has occurred.

https://github-actions-hero.now.sh/playground
https://github-actions-hero.now.sh/lessons/1

**Comment by Gothicania** [comment] 2021-01-02 05:44
https://github.com/cschleiden/github-actions-hero/issues/10#issue-773079008

**Comment by Gothicania** [comment] 2021-01-02 05:44
> [#10 (comment)](https://github.com/cschleiden/github-actions-hero/issues/10#issue-773079008)

**Comment by cschleiden** [comment] 2021-01-03 03:12
Duplicate of https://github.com/cschleiden/github-actions-hero/issues/9

**Closed as completed by cschleiden** 2021-01-03 03:12 UTC
